plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.47.0'
    implementation 'org.testng:testng:7.11.0'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'

    implementation 'net.datafaker:datafaker:2.5.2'

    implementation 'io.appium:java-client:8.3.0'
    implementation 'ch.qos.logback:logback-classic:1.5.25'

    implementation 'com.atlassian:onetime:2.1.2'

}

test {
    useTestNG()
}

tasks.register('smoketests', Test) {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    useTestNG(){
        suites 'src/test/resources/smoketests.xml'
    }
}