name: Smoke tests (Linux)

env:
  TRELLO_EMAIL: ${{ secrets.TRELLO_EMAIL }}
  TRELLO_PASSWORD: ${{ secrets.TRELLO_PASSWORD }}
  TRELLO_TOTP_SECRET: ${{ secrets.TRELLO_TOTP_SECRET }}

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force Sync Clock (Linux)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y chrony
          sudo systemctl enable chrony
          sudo systemctl restart chrony
          sudo chronyc -a 'burst 4/4'
          sudo chronyc -a makestep
          timedatectl status

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean test

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: build/screenshots/
